<program> ::= <importDeclaration>* (<declaration> | <statement> | <funcCall>)* EOF

<declaration> ::= <constDeclaration>
                | <varDeclaration>
                | <funcDeclaration>
                | <classDeclaration>
                | <importDeclaration>
                | <exportDeclaration>

<importDeclaration> ::= 'from' IDENTIFIER 'import' <importList> ';'

<importList> ::= <importItem> (',' <importItem>)*

<importItem> ::= UPPERCASE_IDENTIFIER
               | CLASS_IDENTIFIER
               | IDENTIFIER

<exportDeclaration> ::= 'export' (<classDeclaration> | <funcDeclaration> | <constDeclaration>)

<classDeclaration> ::= 'class' CLASS_IDENTIFIER ('extends' CLASS_IDENTIFIER)? '{' (<publicBlock>)? (<privateBlock>)? '}'

<publicBlock> ::= 'public' '{' (<varDeclaration> | <constructorDeclaration> | <methodDeclaration>)* '}'

<privateBlock> ::= 'private' '{' (<varDeclaration> | <constructorDeclaration> | <methodDeclaration>)* '}'

<constructorDeclaration> ::= CLASS_IDENTIFIER '(' <paramList>? ')' '{' (<constructorInitStatement> | <assignmentStatement> | <superCall>)* '}'

<superCall> ::= 'super' '(' (<expr> (',' <expr>)*)? ')' ';'

<constructorInitStatement> ::= 'this' '.' IDENTIFIER '=' <expr> ';'

<methodDeclaration> ::= <type> 'func' IDENTIFIER '(' <paramList>? ')' <block>
                      | 'func' IDENTIFIER '(' <paramList>? ')' <block>

<constDeclaration> ::= 'const' <type> UPPERCASE_IDENTIFIER '=' (<expr> | <arrayLiteral>) ';'

<varDeclaration> ::= <type> IDENTIFIER ('=' (<expr> | <arrayLiteral>))? ';'
                   | <type> IDENTIFIER '=' NEW CLASS_IDENTIFIER '(' (<expr> (',' <expr>)*)? ')' ';'

<statement> ::= <declaration>
              | <assignmentStatement>
              | <arrayAssignmentStatement>
              | <valueAccess>
              | <ifStatement>
              | <forStatement>
              | <whileStatement>
              | <doWhileStatement>
              | <breakStatement>
              | <continueStatement>
              | <returnStmt>
              | <block>
              | <expr> ';'

<whileStatement> ::= 'while' '(' <expr> ')' <block>

<doWhileStatement> ::= 'do' <block> 'while' '(' <expr> ')' ';'

<breakStatement> ::= 'break' ';'

<continueStatement> ::= 'continue' ';'

<forStatement> ::= 'for' '(' IDENTIFIER 'in' <forRange> ')' <block>

<forRange> ::= <rangeExpr>
             | <expr>

<rangeExpr> ::= 'range' '(' <expr> (',' <expr> (',' <expr>)?)? ')'

<builtInCall> ::= 'print' '(' <expr> ')' ';' | <rangeExpr>

<block> ::= '{' <statement>* '}'

<assignmentStatement> ::= IDENTIFIER '=' NEW CLASS_IDENTIFIER '(' (<expr> (',' <expr>)*)? ')' ';'
                        | IDENTIFIER <assignOp> <expr> ';'
                        | 'this' '.' IDENTIFIER <assignOp> <expr> ';'

<arrayAssignmentStatement> ::= <arrayAccess> '=' <expr> ';'

<arrayLiteral> ::= '[' (<expr> (',' <expr>)*)? ']'

<arrayAccess> ::= IDENTIFIER '[' <expr> ']'
                | UPPERCASE_IDENTIFIER '[' <expr> ']'

<ifStatement> ::= 'if' '(' <expr> ')' <block> ('elseif' '(' <expr> ')' <block>)* ('else' <block>)?

<valueAccess> ::= IDENTIFIER '.' (<funcCall> | IDENTIFIER )?

<expr> ::= <expr> <arithmeticOp> <term>
          | <expr> <compareOp> <term>
          | <expr> <logicalOp> <term>
          | <notExpr>
          | <term>

<arithmeticOp> ::= '+'
                 | '-'
                 | '*'
                 | '/'
                 | '**'
                 | '%'

<compareOp> ::= '=='
               | '!='
               | '>='
               | '<='
               | '>'
               | '<'

<logicalOp> ::= AND
               | OR

<assignOp> ::= ASSIGN
              | ADD_ASSIGN
              | SUB_ASSIGN
              | MUL_ASSIGN
              | DIV_ASSIGN

<notExpr> ::= NOT <expr>

<classInstantiation> ::= CLASS_IDENTIFIER '(' (<expr> (',' <expr>)*)? ')'

<term> ::= <factor>
          | 'this' ('.' IDENTIFIER)?

<factor> ::= BOOL_LIT
           | DECIMAL_LIT
           | INT_LIT
           | STRING_LIT
           | IDENTIFIER
           | <funcCall>
           | <arrayAccess>
           | <builtInCall>
           | <classInstantiation>
           | '(' <expr> ')'

<funcDeclaration> ::= <type> 'func' IDENTIFIER '(' <paramList>? ')' <block>
                    | 'func' IDENTIFIER '(' <paramList>? ')' <block>

<funcCall> ::= IDENTIFIER '(' (<expr> (',' <expr>)*)? ')'

<paramList> ::= <param> (',' <param>)*

<param> ::= <type> IDENTIFIER

<returnStmt> ::= 'return' <expr>? ';'

<type> ::= 'number'
         | 'string'
         | 'bool'
         | CLASS_IDENTIFIER
